# Generated by Django 4.1.4 on 2023-06-13 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_alter_category_category_name_and_more'),
        ('marketplace', '0006_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_packages', models.ManyToManyField(to='menu.packageitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
