# Generated by Django 4.1.4 on 2023-06-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_packageitem_address_packageitem_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0007_collaborativerecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_packages', models.ManyToManyField(to='menu.packageitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
