# Generated by Django 4.1.1 on 2023-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_reviewratingpackage_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewratingpackage',
            name='sentiment',
        ),
    ]
