# Generated by Django 4.2.1 on 2023-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_reviewratingpackage_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
