# Generated by Django 4.2.1 on 2023-05-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
