# Generated by Django 4.2.1 on 2023-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
