# Generated by Django 4.2.1 on 2023-06-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_packageitem_address_packageitem_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='menu/packages')),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.packageitem')),
            ],
        ),
    ]
