# Generated by Django 4.2.1 on 2023-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_packageitem_image2_packageitem_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='durations',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='experiences_covered',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='inclusions',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='packageimages'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='packageimages'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='packageimages'),
        ),
    ]
