# Generated by Django 4.2.1 on 2023-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_packageitem_durations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='durations',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='experiences_covered',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='inclusions',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
