# Generated by Django 4.2.1 on 2023-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_packageitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='durations',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='experiences_covered',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='inclusions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
