# Generated by Django 4.2.1 on 2023-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_packageitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
