# Generated by Django 4.2.1 on 2023-06-12 03:25

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_end_date_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=None, max_length=200, null=True, validators=[orders.models.Order.validate_date]),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=None, max_length=200, null=True, validators=[orders.models.Order.validate_date]),
        ),
    ]
