# Generated by Django 4.2.1 on 2023-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0004_openinghour'),
        ('orders', '0004_alter_order_end_date_alter_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
