# Generated by Django 4.2.1 on 2023-06-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
    ]
